import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";

const spaceGrotsek = Space_Grotesk({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "J'pura Xtreme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden inset-0" style={spaceGrotsek.style}>{children}</body>
    </html>
  );
}
